AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambdas used to send transcriptions to SNS when uploaded to an S3 bucket and to send this transcriptions to SNS.

Resources:
  UploadBucket:
    Type: 'AWS::S3::Bucket'

  TranscriptionsBucket:
    Type: 'AWS::S3::Bucket'

  AWSTranscribeRole: 
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - transcribe.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: 'arn:aws:s3:::*/*'
#                Resource: !Join
#                  - ''
#                  - - !GetAtt UploadBucket.Arn
#                    - '/*'
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Join
                  - ''
                  - - !GetAtt TranscriptionsBucket.Arn
                    - '/*'
          PolicyName: AllowGetAndPutToS3Buckets

  SendAudioToTranscribe:
    Type: AWS::Serverless::Function
    Properties:
      Handler: send-audio-to-transcribe/audio-translator-send-audio-to-transcribe.handler
      Runtime: nodejs12.x
      Events:
        AudioUpdated:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events: s3:ObjectCreated:*
      Environment:
        Variables:
          OUTPUT_BUCKET_NAME: !Ref TranscriptionsBucket
          TRANSCRIBE_DATA_ACCESS_ROLE: !GetAtt AWSTranscribeRole.Arn
      Policies:
        - Statement:
          - Effect: Allow
            Resource: '*'
            Action:
              - transcribe:*
          - Effect: Allow
            Resource: '*'
            Action:
              - iam:PassRole
  
  TranscriptionsSNS:
    Type: 'AWS::SNS::Topic'

  SendTranscriptionToSNS:
    Type: AWS::Serverless::Function
    Properties:
      Handler: send-transcription-to-sns/audio-translator-send-transcription-to-sns.handler
      Runtime: nodejs12.x
      Events:
        TranscriptionUpdated:
          Type: S3
          Properties:
            Bucket: !Ref TranscriptionsBucket
            Events: s3:ObjectCreated:*
      Environment:
        Variables:
          OUTPUT_SNS_TOPIC: !Ref TranscriptionsSNS
      Policies:
        - Statement:
          - Effect: Allow
            Resource: !GetAtt TranscriptionsBucket.Arn
            Action:
              - s3:GetObject
          - Effect: Allow
            Resource: !Ref TranscriptionsSNS
            Action:
              - sns:Publish